#
#Mon Apr 27 15:09:24 COT 2026
goog\:chromeOptions={args\=[--headless\=new, --no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, --lang\=es, --ignore-certificate-errors, --disable-popup-blocking, --allow-outdated-plugins, --enable-plugins, --disable-translate, --test-type, --headless\=new, --no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, --lang\=es, --ignore-certificate-errors, --disable-popup-blocking, --allow-outdated-plugins, --enable-plugins, --disable-translate, --test-type, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
