#
#Mon Apr 27 13:23:08 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --lang\=es, --ignore-certificate-errors, --disable-popup-blocking, --allow-outdated-plugins, --enable-plugins, --disable-translate, --test-type, --incognito, --start-maximized, --lang\=es, --ignore-certificate-errors, --disable-popup-blocking, --allow-outdated-plugins, --enable-plugins, --disable-translate, --test-type, --incognito, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
